支持首页随机背景
argvchs/hexo-theme-particlex pull request #62
Opened 2023-03-04 16:24 UTC by IceOfSummer

我在自己本地测试了一下是没有问题的

2023-03-05 06:22 UTC, IceOfSummer commented
我给我我自己的博客用上了: https://iceofsummer.github.io/

仓库: https://github.com/IceOfSummer/iceofsummer.github.io

2023-03-05 15:59 UTC, argvchs commented
https://github.com/argvchs/hexo-theme-particlex/commit/25873c376c09b6b901455329b732a77ccf61c340

最近用 Vue 重构了很多代码所以没有回复。。。

其实可以把这个放到一个 [Mixin](https://github.com/argvchs/hexo-theme-particlex/tree/master/source/js/lib) 里面，就不会单独出来一个和其他很不统一的 `<script>` 了

刚重构完懒得弄了，过几天我再做吧

2023-03-05 16:00 UTC, argvchs requested changes
https://github.com/argvchs/hexo-theme-particlex/commit/25873c376c09b6b901455329b732a77ccf61c340

最近用 Vue 重构了很多代码所以没有回复。。。

其实可以把这个放到一个 [Mixin](https://github.com/argvchs/hexo-theme-particlex/tree/master/source/js/lib) 里面，就不会单独出来一个和其他很不统一的 `<script>` 了

刚重构完懒得弄了，过几天我再做吧

2023-03-05 16:06 UTC, IceOfSummer commented
我明天改一下吧。话说yaml数组被读成了字符串是bug吗，但是我看有些地方好像又是正常的数组

2023-03-06 08:08 UTC, IceOfSummer commented
@argvchs 改好了

话说需要我帮你把代码美化一下吗，，有些地方用ejs写出来确实很难看

2023-03-06 15:02 UTC, argvchs commented
啊。。可是这样每次生成的背景都是一样的了

2023-03-06 15:04 UTC, IceOfSummer commented
> 啊。。可是这样每次生成的背景都是一样的了

没啊，是随机的

2023-03-06 15:07 UTC, argvchs commented
EJS 只生成一次，生成后每次打开都是一样

2023-03-06 15:15 UTC, IceOfSummer commented
这样应该好了吧。

2023-03-06 16:44 UTC, merged